// solid-app/src/components/Counter/CounterDisplay.tsx
import { Component } from "solid-js"

interface CounterDisplayProps {
    countValue: number,
}

const CounterDisplay: Component<CounterDisplayProps> = (props) => {
    console.log("rendering CounterDisplay")

    const doThing = (p: number) => {
        console.log(`rerendered p${p}`)
        return ""
    }

    return (
        <div>
            <p>same element: {props.countValue} {doThing(1)}</p>
            <p>same string: {`${props.countValue} ${doThing(2)}`}</p>
        </div>
    )
}

export default CounterDisplay

// next-app/app/count/CounterDisplay.tsx
interface CounterDisplayProps {
    countValue: number,
}

const CounterDisplay = ({ countValue }: CounterDisplayProps) => {
    console.log("rendering CounterDisplay")

    const doThing = (p: number) => {
        console.log(`rerendered p${p}`)
        return ""
    }

    return (
        <div>
            <p>same element: {countValue} {doThing(1)}</p>
            <p>same string: {`${countValue} ${doThing(2)}`}</p>
        </div>
    )
}

export default CounterDisplay
