// qwik-app/src/routes/layout.tsx
import { component$, Slot } from '@builder.io/qwik';
import { DocumentHead, Link } from '@builder.io/qwik-city';

export default component$(() => {
  console.log("rendering layout")

  return (
    <>
      <title>Qwik</title>
      <Link href="/">Home</Link>{' '}
      <Link href="/count/">Counter</Link>{' '}
      <Link href="/todo/">Todo</Link>
      <Slot />
    </>
  );
});

export const head: DocumentHead = {
  title: "QwikCity"
}

// next-app/app/layout.tsx
import Link from "next/link"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log("rendering layout")

  return (
    <html>
      <head />
      <body>
        <div>
          <Link href={"/"} >Home</Link>{' '}
          <Link href={"/count"} >Count</Link>{' '}
          <Link href={"/todo"} >Todo</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
