// qwik-app/src/routes/todo/AddInput.tsx
import { component$, useSignal, $, QRL } from "@builder.io/qwik";

interface AddInputProps {
    onAddNew$: QRL<(newItem: string) => void>
}

const AddInput = component$<AddInputProps>(({ onAddNew$ }) => {
    console.log("rendering AddInput")
    const newItem = useSignal("")

    const handleAdd = $(() => {
        if (newItem.value !== "") {
            onAddNew$(newItem.value)
            newItem.value = ""
        }
    })

    const doThing = () => {
        console.log("rerendered addInput")
        return ""
    }

    return (
        <div>
            <label>Add New: </label>
            <input
                onChange$={(e) => newItem.value = e.target.value}
                // value={`${doThing()}`}
                value={`${newItem.value}${doThing()}`}
            />
            <button onClick$={handleAdd}>Add</button>
        </div>
    )
})

export default AddInput

// next-app/app/todo/AddInput.tsx
import { useState } from "react"

interface AddInputProps {
    onAddNew: (newItem: string) => void
}

const AddInput = ({ onAddNew }: AddInputProps) => {
    console.log("rendering AddInput")
    const [newItem, setNewItem] = useState("")

    const handleAdd = () => {
        if (newItem !== "") {
            onAddNew(newItem)
            setNewItem("")
        }
    }

    const doThing = () => {
        console.log("rerendered addInput")
        return ""
    }

    return (
        <div>
            <label>Add New: </label>
            <input
                onChange={(e) => setNewItem(e.currentTarget.value)}
                value={`${newItem}${doThing()}`}
            />
            <button onClick={handleAdd}>Add</button>
        </div>
    )
}

export default AddInput
