// qwik-app/src/routes/todo/ModifyInput.tsx
import { component$, useSignal, $, QRL } from "@builder.io/qwik";
import { ItemType } from ".";

interface ModifyItemProps {
    items: ItemType[],
    onModify$: QRL<(id: number, newItem: string) => void>
}

const ModifyItem = component$<ModifyItemProps>(({ items, onModify$ }) => {
    console.log("rendering ModifyInput")
    const idx = useSignal<number>(0)
    const newItem = useSignal("")

    const handleModify = $(() => {
        if (newItem.value !== "") {
            // items[idx.value - 1].item = newItem.value
            onModify$(idx.value - 1, newItem.value)
        }
    })

    const handleIdChange = $((e: Event) => {
        idx.value = (e.target as HTMLInputElement).valueAsNumber
        newItem.value = idx.value > 0 && idx.value <= items.length ? items[idx.value - 1].item : ""
    })

    const doThing = () => {
        console.log("rerendered modifyInput")
        return ""
    }

    return (
        <div>
            <label>Modify: </label>
            <input onInput$={handleIdChange} type="number" placeholder="ID"/>
            <input onChange$={(e) => newItem.value = e.target.value} value={`${newItem.value}${doThing()}`} placeholder="New item"/>
            <button onClick$={handleModify}>Modify</button>
        </div>
    )
})

export default ModifyItem

// next-app/app/todo/ModifyInput.tsx
import { FormEventHandler, useState } from "react";
import { ItemType } from "./page";

interface ModifyInputProps {
    onModify: (id: number, newItem: string) => void,
    items: ItemType[],
}

const ModifyItem = ({ onModify, items }: ModifyInputProps) => {
    console.log("rendering ModifyInput")
    const [idx, setIdx] = useState(0)
    const [newItem, setNewItem] = useState("")

    const handleModify = () => {
        if (newItem !== "") {
            onModify(idx - 1, newItem)
            // props.setItems(idx() - 1, "item", newItem())
        }
    }

    const handleIdChange: FormEventHandler<HTMLInputElement> = (e) => {
        const idx = e.currentTarget.valueAsNumber
        setIdx(idx)
        setNewItem(idx > 0 && idx <= items.length ? items[idx - 1].item : "")
    }

    const doThing = () => {
        console.log("rerendered modifyInput")
        return ""
    }

    return (
        <div>
            <label>Modify: </label>
            <input onInput={handleIdChange} type="number" placeholder="ID"/>
            <input onChange={(e) => setNewItem(e.currentTarget.value)} value={`${newItem}${doThing()}`} placeholder="New item"/>
            <button onClick={handleModify}>Modify</button>
        </div>
    )
}

export default ModifyItem
