// solid-app/src/routes/(index)/todo.tsx
import { For } from "solid-js";
import { createStore } from "solid-js/store";
import AddInput from "~/components/Todo/AddInput";
import ModifyItem from "~/components/Todo/ModifyInput";
import TodoItem from "~/components/Todo/TodoItem";

export interface ItemType {
    id: number
    item: string
}

export default function Todo() {
    console.log("rendering todo")
    const [items, setItems] = createStore<ItemType[]>([
        { id: 1, item: "do work"},
        { id: 2, item: "do stuff"},
        { id: 3, item: "do jazz"},
    ])
    let ct = items.length

    const addItem = (newItem: string) => {
        setItems(ls => [...ls, { id: ++ct, item: newItem }])
    }

    const modifyItem = (idx: number, newItem: string) => {
        setItems(idx, "item", newItem)
    }

    const deleteItem = (id: number) => {
        setItems(ls => ls.filter((item) => item.id !== id))
    }

    const doThing = (idx: number) => {
        console.log("rendering item", idx, "in loop")
        return ""
    }

    return (
        <div>
            <h1>Todo List</h1>
            <p>Check console to see how state affects rerenders</p>
            <AddInput onAddNew={addItem} />
            <br></br>
            <ModifyItem items={items} onModify={modifyItem} />
            {/* <ModifyItem items={items} onModify={modifyItem} setItems={setItems}/> */}
            <ol>
                <For each={items}>
                    {(item, idx) => {
                        doThing(idx())
                        // return <TodoItem item={item} onDelete={deleteItem} setItems={setItems}/>
                        return <TodoItem item={item} setItems={setItems}/>
                    }}
                </For>
            </ol>
        </div>
    );
}

// next-app/app/todo/page.tsx
"use client";

import { useRef, useState } from "react"
import AddInput from "./AddInput";
import ModifyItem from "./ModifyInput";
import TodoItem from "./TodoItem"

export interface ItemType {
    id: number
    item: string
}


export default function Todo() {
    console.log("rendering todo")
    const [items, setItems] = useState<ItemType[]>([
        { id: 1, item: "do work"},
        { id: 2, item: "do stuff"},
        { id: 3, item: "do jazz"},
    ])
    const ct = useRef(items.length)

    const addItem = (newItem: string) => {
        setItems([...items, { id: ++ct.current, item: newItem }])
    }

    const modifyItem = (idx: number, newItem: string) => {
        const newItems = [...items]
        newItems[idx].item = newItem
        setItems(newItems)
    }

    const doThing = (idx: number) => {
        console.log("rendering item", idx, "in loop")
        return ""
    }

    return (
        <div>
            <h1>Todo List</h1>
            <p>Check console to see how state affects rerenders</p>
            <AddInput onAddNew={addItem} />
            <br></br>
            <ModifyItem items={items} onModify={modifyItem} />
            <ol>
                {items.map((item, idx) => {
                    doThing(idx)
                    // return <TodoItem item={item} onDelete={deleteItem}/>
                    return <TodoItem key={item.id} item={item} setItems={setItems}/>
                })}
            </ol>
        </div>
    )
}
